const estados = {
    "ABC":                                 { estado: "Rio Grande do Norte",  uf: "RN" },
    "Alecrim":                             { estado: "Rio Grande do Norte",  uf: "RN" },
    "Alegrense":                           { estado: "Espírito Santo",       uf: "ES" },
    "América de Teófilo Otoni":            { estado: "Minas Gerais",         uf: "MG" },
    "América de Três Rios":                { estado: "Rio de Janeiro",       uf: "RJ" },
    "América SJ Rio Preto":                { estado: "São Paulo",            uf: "SP" },
    "América-MG":                          { estado: "Minas Gerais",         uf: "MG" },
    "América-PE":                          { estado: "Pernambuco",           uf: "PE" },
    "América-RJ":                          { estado: "Rio de Janeiro",       uf: "RJ" },
    "América-RN":                          { estado: "Rio Grande do Norte",  uf: "RN" },
    "América-SC":                          { estado: "Santa Catarina",       uf: "SC" },
    "Americano":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Americano-SP":                        { estado: "São Paulo",            uf: "SP" },
    "Anapolina":                           { estado: "Goiás",                uf: "GO" },
    "Anápolis":                            { estado: "Goiás",                uf: "GO" },
    "Andarahy":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Aparecidense":                        { estado: "Goiás",                uf: "GO" },
    "Araranguá":                           { estado: "Santa Catarina",       uf: "SC" },
    "Araxá":                               { estado: "Minas Gerais",         uf: "MG" },
    "Asas de Lagoa Santa":                 { estado: "Minas Gerais",         uf: "MG" },
    "Associação das Palmeiras":            { estado: "São Paulo",            uf: "SP" },
    "Athletic":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Athletico-PR":                        { estado: "Paraná",               uf: "PR" },
    "Atlético de Cajazeiras":              { estado: "Paraíba",              uf: "PB" },
    "Atlético de Três Corações":           { estado: "Minas Gerais",         uf: "MG" },
    "Atlético Operário":                   { estado: "Santa Catarina",       uf: "SC" },
    "Atlético-GO":                         { estado: "Goiás",                uf: "GO" },
    "Atlético-MG":                         { estado: "Minas Gerais",         uf: "MG" },
    "Atlético-PR":                         { estado: "Paraná",               uf: "PR" },
    "Audax Rio":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Auto Esporte":                        { estado: "Paraíba",              uf: "PB" },
    "Avaí":                                { estado: "Santa Catarina",       uf: "SC" },
    "Aymorés":                             { estado: "Minas Gerais",         uf: "MG" },
    "Bahia":                               { estado: "Bahia",                uf: "BA" },
    "Bahia de Feira":                      { estado: "Bahia",                uf: "BA" },
    "Bancário":                            { estado: "Rio Grande do Sul",    uf: "RS" },
    "Bangu":                               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Baraúnas":                            { estado: "Rio Grande do Norte",  uf: "RN" },
    "Barra da Tijuca":                     { estado: "Rio de Janeiro",       uf: "RJ" },
    "Barra Mansa":                         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Blumenau":                            { estado: "Santa Catarina",       uf: "SC" },
    "Boa Esporte":                         { estado: "Minas Gerais",         uf: "MG" },
    "Boavista":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Bonsucesso":                          { estado: "Rio de Janeiro",       uf: "RJ" },
    "Botafogo-BA":                         { estado: "Bahia",                uf: "BA" },
    "Botafogo-PB":                         { estado: "Paraíba",              uf: "PB" },
    "Botafogo-SP":                         { estado: "São Paulo",            uf: "SP" },
    "Bragantino":                          { estado: "São Paulo",            uf: "SP" },
    "Brasil de Pelotas":                   { estado: "Rio Grande do Sul",    uf: "RS" },
    "Brasília":                            { estado: "Distrito Federal",     uf: "DF" },
    "Brasiliense":                         { estado: "Distrito Federal",     uf: "DF" },
    "Britânia":                            { estado: "Paraná",               uf: "PR" },
    "Brusque":                             { estado: "Santa Catarina",       uf: "SC" },
    "Byron":                               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Cabofriense":                         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Caldense":                            { estado: "Minas Gerais",         uf: "MG" },
    "Calouros do Ar":                      { estado: "Ceará",                uf: "CE" },
    "Campinense":                          { estado: "Paraíba",              uf: "PB" },
    "Campo Grande":                        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Campo Grande-RJ":                     { estado: "Rio de Janeiro",       uf: "RJ" },
    "Cantagalo":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Canto do Rio":                        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Capital":                             { estado: "Distrito Federal",     uf: "DF" },
    "Capivariano":                         { estado: "São Paulo",            uf: "SP" },
    "Cardoso Moreira":                     { estado: "Rio de Janeiro",       uf: "RJ" },
    "Carioca FC":                          { estado: "Rio de Janeiro",       uf: "RJ" },
    "Carlos Renaux":                       { estado: "Santa Catarina",       uf: "SC" },
    "Catanduva":                           { estado: "São Paulo",            uf: "SP" },
    "Cattete":                             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Caxias":                              { estado: "Rio Grande do Sul",    uf: "RS" },
    "Ceará":                               { estado: "Ceará",                uf: "CE" },
    "Ceilândia":                           { estado: "Distrito Federal",     uf: "DF" },
    "CENE":                                { estado: "Mato Grosso do Sul",   uf: "MS" },
    "Central":                             { estado: "Pernambuco",           uf: "PE" },
    "CEUB":                                { estado: "Distrito Federal",     uf: "DF" },
    "CFZ":                                 { estado: "Rio de Janeiro",       uf: "RJ" },
    "Chapecoense":                         { estado: "Santa Catarina",       uf: "SC" },
    "Cocotá":                              { estado: "Rio de Janeiro",       uf: "RJ" },
    "Colatina":                            { estado: "Espírito Santo",       uf: "ES" },
    "Colégio Militar":                     { estado: "Rio de Janeiro",       uf: "RJ" },
    "Colo-Colo-BA":                        { estado: "Bahia",                uf: "BA" },
    "Colorado":                            { estado: "Paraná",               uf: "PR" },
    "Combinado 2ª Divisão-MG":             { estado: "Minas Gerais",         uf: "MG" },
    "Combinado América-MG/Villa Nova":     { estado: "Minas Gerais",         uf: "MG" },
    "Combinado Carioca":                   { estado: "Rio de Janeiro",       uf: "RJ" },
    "Combinado Cruzeiro/América-MG":       { estado: "Minas Gerais",         uf: "MG" },
    "Combinado da Zona Norte":             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Combinado de Macaé":                  { estado: "Rio de Janeiro",       uf: "RJ" },
    "Combinado do Pará":                   { estado: "Pará",                 uf: "PA" },
    "Combinado do Rio de Janeiro":         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Combinado Moto Club/Sampaio Correa":  { estado: "Maranhão",             uf: "MA" },
    "Combinado Tocantins/Imperatriz":      { estado: "Maranhão",             uf: "MA" },
    "Combinado Tupi/Tupynambás":           { estado: "Minas Gerais",         uf: "MG" },
    "Comercial-MG":                        { estado: "Minas Gerais",         uf: "MG" },
    "Comercial-MS":                        { estado: "Mato Grosso do Sul",   uf: "MS" },
    "Comercial-SP":                        { estado: "São Paulo",            uf: "SP" },
    "Confiança":                           { estado: "Sergipe",              uf: "SE" },
    "Confiança-RJ":                        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Corinthians":                         { estado: "São Paulo",            uf: "SP" },
    "Corisabbá":                           { estado: "Piauí",                uf: "PI" },
    "Coritiba":                            { estado: "Paraná",               uf: "PR" },
    "Corumbaense":                         { estado: "Mato Grosso do Sul",   uf: "MS" },
    "Coruripe":                            { estado: "Alagoas",              uf: "AL" },
    "CRB":                                 { estado: "Alagoas",              uf: "AL" },
    "Criciúma":                            { estado: "Santa Catarina",       uf: "SC" },
    "Cruzeiro":                            { estado: "Minas Gerais",         uf: "MG" },
    "Cruzeiro-RS":                         { estado: "Rio Grande do Sul",    uf: "RS" },
    "CSA":                                 { estado: "Alagoas",              uf: "AL" },
    "Cuiabá":                              { estado: "Mato Grosso",          uf: "MT" },
    "Democrata GV":                        { estado: "Minas Gerais",         uf: "MG" },
    "Democrata SL":                        { estado: "Minas Gerais",         uf: "MG" },
    "Desportiva Ferroviária":              { estado: "Espírito Santo",       uf: "ES" },
    "Dom Pedro":                           { estado: "Distrito Federal",     uf: "DF" },
    "Duque de Caxias":                     { estado: "Rio de Janeiro",       uf: "RJ" },
    "Duquecaxiense":                       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Engenho de Dentro":                   { estado: "Rio de Janeiro",       uf: "RJ" },
    "Entrerriense":                        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Estrela do Norte":                    { estado: "Rio de Janeiro",       uf: "RJ" },
    "Fabril":                              { estado: "Minas Gerais",         uf: "MG" },
    "Fabril Atlético":                     { estado: "Minas Gerais",         uf: "MG" },
    "Fast Clube":                          { estado: "Amazonas",             uf: "AM" },
    "Ferroviária":                         { estado: "São Paulo",            uf: "SP" },
    "Ferroviário-CE":                      { estado: "Ceará",                uf: "CE" },
    "Ferroviário-PR":                      { estado: "Paraná",               uf: "PR" },
    "Figueirense":                         { estado: "Santa Catarina",       uf: "SC" },
    "Flamengo":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Flamengo-PI":                         { estado: "Piauí",                uf: "PI" },
    "Floriano":                            { estado: "Piauí",                uf: "PI" },
    "Fluminense":                          { estado: "Rio de Janeiro",       uf: "RJ" },
    "Fluminense de Araguari":              { estado: "Minas Gerais",         uf: "MG" },
    "Fluminense de Feira":                 { estado: "Bahia",                uf: "BA" },
    "Fonseca":                             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Football and Athletic":               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Força e Luz":                         { estado: "Rio Grande do Sul",    uf: "RS" },
    "Fortaleza":                           { estado: "Ceará",                uf: "CE" },
    "Friburgo":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Friburguense":                        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Galícia":                             { estado: "Bahia",                uf: "BA" },
    "Gama":                                { estado: "Distrito Federal",     uf: "DF" },
    "Germânia-RJ":                         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Germânia-SP":                         { estado: "São Paulo",            uf: "SP" },
    "Goiânia":                             { estado: "Goiás",                uf: "GO" },
    "Goiás":                               { estado: "Goiás",                uf: "GO" },
    "Goytacaz":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Grêmio":                              { estado: "Rio Grande do Sul",    uf: "RS" },
    "Grêmio Maringá":                      { estado: "Paraná",               uf: "PR" },
    "Grêmio Prudente":                     { estado: "São Paulo",            uf: "SP" },
    "Guanabara":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Guará":                               { estado: "Distrito Federal",     uf: "DF" },
    "Guarani":                             { estado: "São Paulo",            uf: "SP" },
    "Guarani de Ponta Grossa":             { estado: "Paraná",               uf: "PR" },
    "Guarani-MG":                          { estado: "Minas Gerais",         uf: "MG" },
    "Guarany de Bagé":                     { estado: "Rio Grande do Sul",    uf: "RS" },
    "Guarapari":                           { estado: "Espírito Santo",       uf: "ES" },
    "Haddock Lobo":                        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Hellênico":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Hepacaré":                            { estado: "São Paulo",            uf: "SP" },
    "Icasa":                               { estado: "Ceará",                uf: "CE" },
    "Inter de Lages":                      { estado: "Santa Catarina",       uf: "SC" },
    "Inter de Limeira":                    { estado: "São Paulo",            uf: "SP" },
    "Internacional":                       { estado: "Rio Grande do Sul",    uf: "RS" },
    "Internacional de Bebedouro":          { estado: "São Paulo",            uf: "SP" },
    "Internacional de Petrópolis":         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Internacional-BA":                    { estado: "Bahia",                uf: "BA" },
    "Internacional-RJ":                    { estado: "Rio de Janeiro",       uf: "RJ" },
    "Internacional-SP":                    { estado: "São Paulo",            uf: "SP" },
    "Ipatinga":                            { estado: "Minas Gerais",         uf: "MG" },
    "Ipiranga de Manhuaçu":                { estado: "Minas Gerais",         uf: "MG" },
    "Itabaiana":                           { estado: "Sergipe",              uf: "SE" },
    "Itabuna":                             { estado: "Bahia",                uf: "BA" },
    "Itaperuna":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Jequié":                              { estado: "Bahia",                uf: "BA" },
    "Ji-Paraná":                           { estado: "Rondônia",             uf: "RO" },
    "Joinville":                           { estado: "Santa Catarina",       uf: "SC" },
    "Juazeirense":                         { estado: "Bahia",                uf: "BA" },
    "Juventude":                           { estado: "Rio Grande do Sul",    uf: "RS" },
    "Juventus-SC":                         { estado: "Santa Catarina",       uf: "SC" },
    "Londrina":                            { estado: "Paraná",               uf: "PR" },
    "Luve":                                { estado: "Minas Gerais",         uf: "MG" },
    "Luverdense":                          { estado: "Mato Grosso",          uf: "MT" },
    "Luziânia":                            { estado: "Goiás",                uf: "GO" },
    "Macaé":                               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Machadense":                          { estado: "Minas Gerais",         uf: "MG" },
    "Mackenzie":                           { estado: "São Paulo",            uf: "SP" },
    "Madureira":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Manchester-MG":                       { estado: "Minas Gerais",         uf: "MG" },
    "Mangueira":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Maranhão":                            { estado: "Maranhão",             uf: "MA" },
    "Marcílio Dias":                       { estado: "Santa Catarina",       uf: "SC" },
    "Maricá":                              { estado: "Rio de Janeiro",       uf: "RJ" },
    "Marília":                             { estado: "São Paulo",            uf: "SP" },
    "Mavilis":                             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Mesquita":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Metalúrgico":                         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Metropol":                            { estado: "Santa Catarina",       uf: "SC" },
    "Mirassol":                            { estado: "São Paulo",            uf: "SP" },
    "Mixto":                               { estado: "Mato Grosso",          uf: "MT" },
    "Mogi Mirim":                          { estado: "São Paulo",            uf: "SP" },
    "Mogiana":                             { estado: "São Paulo",            uf: "SP" },
    "Moto Club":                           { estado: "Maranhão",             uf: "MA" },
    "Nacional de Patos":                   { estado: "Paraíba",              uf: "PB" },
    "Nacional-AM":                         { estado: "Amazonas",             uf: "AM" },
    "Náutico":                             { estado: "Pernambuco",           uf: "PE" },
    "Niterói":                             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Noroeste":                            { estado: "São Paulo",            uf: "SP" },
    "Nova Cidade":                         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Nova Iguaçu":                         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Nova Venécia":                        { estado: "Espírito Santo",       uf: "ES" },
    "Novorizontino":                       { estado: "São Paulo",            uf: "SP" },
    "Oeste":                               { estado: "São Paulo",            uf: "SP" },
    "Olaria":                              { estado: "Rio de Janeiro",       uf: "RJ" },
    "Olímpica de Lavras":                  { estado: "Minas Gerais",         uf: "MG" },
    "Olympic":                             { estado: "Minas Gerais",         uf: "MG" },
    "Operário-MS":                         { estado: "Mato Grosso do Sul",   uf: "MS" },
    "Operário-MT":                         { estado: "Mato Grosso",          uf: "MT" },
    "Operário-PR":                         { estado: "Paraná",               uf: "PR" },
    "Palmeiras":                           { estado: "São Paulo",            uf: "SP" },
    "Palmeiras-RJ":                        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Paraná":                              { estado: "Paraná",               uf: "PR" },
    "Parnahyba":                           { estado: "Piauí",                uf: "PI" },
    "Passense":                            { estado: "Minas Gerais",         uf: "MG" },
    "Pastoril":                            { estado: "Minas Gerais",         uf: "MG" },
    "Paulista":                            { estado: "São Paulo",            uf: "SP" },
    "Paulistano-RJ":                       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Paulistano-SP":                       { estado: "São Paulo",            uf: "SP" },
    "Paysandu":                            { estado: "Pará",                 uf: "PA" },
    "Paysandu-RJ":                         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Pelotas":                             { estado: "Rio Grande do Sul",    uf: "RS" },
    "Petropolitano":                       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Piauí":                               { estado: "Piauí",                uf: "PI" },
    "Pinheiros":                           { estado: "São Paulo",            uf: "SP" },
    "Ponte Preta":                         { estado: "São Paulo",            uf: "SP" },
    "Porto Alegre-RJ":                     { estado: "Rio de Janeiro",       uf: "RJ" },
    "Portuguesa":                          { estado: "São Paulo",            uf: "SP" },
    "Portuguesa Santista":                 { estado: "São Paulo",            uf: "SP" },
    "Portuguesa-RJ":                       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Potyguar":                            { estado: "Rio Grande do Norte",  uf: "RN" },
    "Quissamã":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Red Bull Bragantino":                 { estado: "São Paulo",            uf: "SP" },
    "Remo":                                { estado: "Pará",                 uf: "PA" },
    "Renner":                              { estado: "Rio Grande do Sul",    uf: "RS" },
    "Resende":                             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Riachuelo":                           { estado: "Rio Grande do Norte",  uf: "RN" },
    "Ribeiro Junqueira":                   { estado: "Minas Gerais",         uf: "MG" },
    "Rio Branco-AC":                       { estado: "Acre",                 uf: "AC" },
    "Rio Branco-ES":                       { estado: "Espírito Santo",       uf: "ES" },
    "Rio Branco-PR":                       { estado: "Paraná",               uf: "PR" },
    "Rio Branco-RJ":                       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Rio Cricket":                         { estado: "Rio de Janeiro",       uf: "RJ" },
    "Rio Grande":                          { estado: "Rio Grande do Sul",    uf: "RS" },
    "Rio Negro":                           { estado: "Amazonas",             uf: "AM" },
    "Rio Preto":                           { estado: "São Paulo",            uf: "SP" },
    "Riograndense":                        { estado: "Rio Grande do Sul",    uf: "RS" },
    "River Plate-SE":                      { estado: "Sergipe",              uf: "SE" },
    "River-PI":                            { estado: "Piauí",                uf: "PI" },
    "River-RJ":                            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Royal":                               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Saad":                                { estado: "São Paulo",            uf: "SP" },
    "Sampaio Corrêa":                      { estado: "Maranhão",             uf: "MA" },
    "Sampaio Corrêa-RJ":                   { estado: "Rio de Janeiro",       uf: "RJ" },
    "Santa Cruz":                          { estado: "Pernambuco",           uf: "PE" },
    "Santo André":                         { estado: "São Paulo",            uf: "SP" },
    "Santo Antônio":                       { estado: "Espírito Santo",       uf: "ES" },
    "Santos":                              { estado: "São Paulo",            uf: "SP" },
    "Santos-ES":                           { estado: "Espírito Santo",       uf: "ES" },
    "São Bento":                           { estado: "São Paulo",            uf: "SP" },
    "São Caetano":                         { estado: "São Paulo",            uf: "SP" },
    "São Cristóvão":                       { estado: "Rio de Janeiro",       uf: "RJ" },
    "São Francisco":                       { estado: "Pará",                 uf: "PA" },
    "São José-SP":                         { estado: "São Paulo",            uf: "SP" },
    "São Paulo":                           { estado: "São Paulo",            uf: "SP" },
    "São Paulo Athletic":                  { estado: "São Paulo",            uf: "SP" },
    "São Raimundo-AM":                     { estado: "Amazonas",             uf: "AM" },
    "São Raimundo-PA":                     { estado: "Pará",                 uf: "PA" },
    "São Raimundo-RR":                     { estado: "Roraima",              uf: "RR" },
    "SC Americano-RJ":                     { estado: "Rio de Janeiro",       uf: "RJ" },
    "SC Brasil":                           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção da Bahia":                    { estado: "Bahia",                uf: "BA" },
    "Seleção de Araguari":                 { estado: "Minas Gerais",         uf: "MG" },
    "Seleção de Barbacena":                { estado: "Minas Gerais",         uf: "MG" },
    "Seleção de Barreiras":                { estado: "Bahia",                uf: "BA" },
    "Seleção de Brasília":                 { estado: "Distrito Federal",     uf: "DF" },
    "Seleção de Campo Grande-MS":          { estado: "Mato Grosso do Sul",   uf: "MS" },
    "Seleção de Foz do Iguaçu":            { estado: "Paraná",               uf: "PR" },
    "Seleção de Ilhéus":                   { estado: "Bahia",                uf: "BA" },
    "Seleção de Itabuna":                  { estado: "Bahia",                uf: "BA" },
    "Seleção de Itaituba":                 { estado: "Pará",                 uf: "PA" },
    "Seleção de Itajubá":                  { estado: "Minas Gerais",         uf: "MG" },
    "Seleção de Juiz de Fora":             { estado: "Minas Gerais",         uf: "MG" },
    "Seleção de Macaé":                    { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção de Minas Gerais":             { estado: "Minas Gerais",         uf: "MG" },
    "Seleção de Niterói":                  { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção de Niterói-AFSA":             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção de Niterói-ANEA":             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção de Nova Friburgo":            { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção de Pernambuco":               { estado: "Pernambuco",           uf: "PE" },
    "Seleção de Petrolina":                { estado: "Pernambuco",           uf: "PE" },
    "Seleção de Petrópolis":               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção de Rondônia":                 { estado: "Rondônia",             uf: "RO" },
    "Seleção de Santa Catarina":           { estado: "Santa Catarina",       uf: "SC" },
    "Seleção de Santarém":                 { estado: "Pará",                 uf: "PA" },
    "Seleção de São Paulo":                { estado: "São Paulo",            uf: "SP" },
    "Seleção de Saquarema":                { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção de Senhor do Bonfim":         { estado: "Bahia",                uf: "BA" },
    "Seleção de Teófilo Otoni":            { estado: "Minas Gerais",         uf: "MG" },
    "Seleção de Ubá":                      { estado: "Minas Gerais",         uf: "MG" },
    "Seleção de Uruguaiana":               { estado: "Rio Grande do Sul",    uf: "RS" },
    "Seleção do Amapá":                    { estado: "Amapá",                uf: "AP" },
    "Seleção do Amazonas":                 { estado: "Amazonas",             uf: "AM" },
    "Seleção do Espírito Santo":           { estado: "Espírito Santo",       uf: "ES" },
    "Seleção do Maranhão":                 { estado: "Maranhão",             uf: "MA" },
    "Seleção do Pará":                     { estado: "Pará",                 uf: "PA" },
    "Seleção do Paraná":                   { estado: "Paraná",               uf: "PR" },
    "Seleção do Rio de Janeiro":           { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção do RS":                       { estado: "Rio Grande do Sul",    uf: "RS" },
    "Seleção dos Ingleses da LMSA":        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleção Rio de Janeiro-AMEA B":       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Seleto":                              { estado: "Paraná",               uf: "PR" },
    "Sergipe":                             { estado: "Sergipe",              uf: "SE" },
    "Serrano":                             { estado: "Rio de Janeiro",       uf: "RJ" },
    "Smart":                               { estado: "Minas Gerais",         uf: "MG" },
    "Sobradinho":                          { estado: "Distrito Federal",     uf: "DF" },
    "Social":                              { estado: "Minas Gerais",         uf: "MG" },
    "South American":                      { estado: "Rio de Janeiro",       uf: "RJ" },
    "Sport":                               { estado: "Pernambuco",           uf: "PE" },
    "Sport-MG":                            { estado: "Minas Gerais",         uf: "MG" },
    "Sportivo de Petrópolis":              { estado: "Rio de Janeiro",       uf: "RJ" },
    "Sul América":                         { estado: "Amazonas",             uf: "AM" },
    "Syrio e Libanez":                     { estado: "Rio de Janeiro",       uf: "RJ" },
    "Syrio-SP":                            { estado: "São Paulo",            uf: "SP" },
    "Taguatinga":                          { estado: "Distrito Federal",     uf: "DF" },
    "Tamoio":                              { estado: "Rio de Janeiro",       uf: "RJ" },
    "Taubaté":                             { estado: "São Paulo",            uf: "SP" },
    "Tigres do Brasil":                    { estado: "Rio de Janeiro",       uf: "RJ" },
    "Tijuco":                              { estado: "Minas Gerais",         uf: "MG" },
    "Tiradentes-DF":                       { estado: "Distrito Federal",     uf: "DF" },
    "Tiradentes-PI":                       { estado: "Piauí",                uf: "PI" },
    "Torre":                               { estado: "Pernambuco",           uf: "PE" },
    "Treze":                               { estado: "Paraíba",              uf: "PB" },
    "Tuna Luso":                           { estado: "Pará",                 uf: "PA" },
    "Tupi":                                { estado: "Minas Gerais",         uf: "MG" },
    "Tupynambás":                          { estado: "Minas Gerais",         uf: "MG" },
    "Uberaba":                             { estado: "Minas Gerais",         uf: "MG" },
    "Uberlândia":                          { estado: "Minas Gerais",         uf: "MG" },
    "Umuarama":                            { estado: "Paraná",               uf: "PR" },
    "União Carvalheira":                   { estado: "Rio de Janeiro",       uf: "RJ" },
    "União Esportiva":                     { estado: "Pará",                 uf: "PA" },
    "União São João":                      { estado: "São Paulo",            uf: "SP" },
    "Usina Ceará":                         { estado: "Ceará",                uf: "CE" },
    "Usipa":                               { estado: "Minas Gerais",         uf: "MG" },
    "Valeriodoce":                         { estado: "Minas Gerais",         uf: "MG" },
    "Vasco":                               { estado: "Rio de Janeiro",       uf: "RJ" },
    "Vila Nova":                           { estado: "Goiás",                uf: "GO" },
    "Villa Isabel":                        { estado: "Rio de Janeiro",       uf: "RJ" },
    "Villa Nova":                          { estado: "Minas Gerais",         uf: "MG" },
    "Vitória":                             { estado: "Bahia",                uf: "BA" },
    "Vitória-ES":                          { estado: "Espírito Santo",       uf: "ES" },
    "Volta Redonda":                       { estado: "Rio de Janeiro",       uf: "RJ" },
    "Ypiranga":                            { estado: "Rio Grande do Sul",    uf: "RS" },
    "Ypiranga de Niterói":                 { estado: "Rio de Janeiro",       uf: "RJ" },
    "Ypiranga-BA":                         { estado: "Bahia",                uf: "BA" },
};

export default estados;
